// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paychex/paychex/payroll.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Payroll struct {
	Year      int32  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month     int32  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Employees uint64 `protobuf:"varint,3,opt,name=employees,proto3" json:"employees,omitempty"`
}

func (m *Payroll) Reset()         { *m = Payroll{} }
func (m *Payroll) String() string { return proto.CompactTextString(m) }
func (*Payroll) ProtoMessage()    {}
func (*Payroll) Descriptor() ([]byte, []int) {
	return fileDescriptor_1267731baf11c779, []int{0}
}
func (m *Payroll) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payroll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payroll.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payroll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payroll.Merge(m, src)
}
func (m *Payroll) XXX_Size() int {
	return m.Size()
}
func (m *Payroll) XXX_DiscardUnknown() {
	xxx_messageInfo_Payroll.DiscardUnknown(m)
}

var xxx_messageInfo_Payroll proto.InternalMessageInfo

func (m *Payroll) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Payroll) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Payroll) GetEmployees() uint64 {
	if m != nil {
		return m.Employees
	}
	return 0
}

func init() {
	proto.RegisterType((*Payroll)(nil), "paychex.paychex.Payroll")
}

func init() { proto.RegisterFile("paychex/paychex/payroll.proto", fileDescriptor_1267731baf11c779) }

var fileDescriptor_1267731baf11c779 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x48, 0xac, 0x4c,
	0xce, 0x48, 0xad, 0xd0, 0x47, 0xa2, 0x8b, 0xf2, 0x73, 0x72, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0xf8, 0xa1, 0xc2, 0x7a, 0x50, 0x5a, 0x29, 0x90, 0x8b, 0x3d, 0x00, 0xa2, 0x42, 0x48, 0x88,
	0x8b, 0xa5, 0x32, 0x35, 0xb1, 0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xcc, 0x16, 0x12,
	0xe1, 0x62, 0xcd, 0xcd, 0xcf, 0x2b, 0xc9, 0x90, 0x60, 0x02, 0x0b, 0x42, 0x38, 0x42, 0x32, 0x5c,
	0x9c, 0xa9, 0xb9, 0x05, 0x39, 0xf9, 0x95, 0xa9, 0xa9, 0xc5, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x2c,
	0x41, 0x08, 0x01, 0x27, 0xc3, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48,
	0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x12,
	0x87, 0x39, 0x0a, 0xe1, 0xbc, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0, 0xeb, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x21, 0x34, 0x0e, 0xbe, 0x00, 0x00, 0x00,
}

func (m *Payroll) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payroll) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payroll) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Employees != 0 {
		i = encodeVarintPayroll(dAtA, i, uint64(m.Employees))
		i--
		dAtA[i] = 0x18
	}
	if m.Month != 0 {
		i = encodeVarintPayroll(dAtA, i, uint64(m.Month))
		i--
		dAtA[i] = 0x10
	}
	if m.Year != 0 {
		i = encodeVarintPayroll(dAtA, i, uint64(m.Year))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPayroll(dAtA []byte, offset int, v uint64) int {
	offset -= sovPayroll(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Payroll) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Year != 0 {
		n += 1 + sovPayroll(uint64(m.Year))
	}
	if m.Month != 0 {
		n += 1 + sovPayroll(uint64(m.Month))
	}
	if m.Employees != 0 {
		n += 1 + sovPayroll(uint64(m.Employees))
	}
	return n
}

func sovPayroll(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPayroll(x uint64) (n int) {
	return sovPayroll(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Payroll) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayroll
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payroll: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payroll: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Year", wireType)
			}
			m.Year = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayroll
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Year |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Month", wireType)
			}
			m.Month = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayroll
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Month |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Employees", wireType)
			}
			m.Employees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayroll
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Employees |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPayroll(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayroll
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPayroll(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPayroll
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayroll
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayroll
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPayroll
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPayroll
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPayroll
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPayroll        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayroll          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPayroll = fmt.Errorf("proto: unexpected end of group")
)
